### ISSUE TITLE
You need to set `$ git config --global user.name "miyon2"` in your terminal

### ISSUE THREAD

**Issue by punkyoon** [miyon2/TIL#2]
@miyon2 

You need to set `$ git config --global user.name "miyon2"` in your terminal

In your commit logs, you can check your anonymous user commits.....

so there's no contributor in this repository..

plz check this issue and resolve it (asap)

**Comment by punkyoon** [comment]
@miyon2 you should close this issue..

**Comment by miyon2** [comment]
oh....really..? how...? 8ㅅ8.....?...........8ㅁ8
